version: "2"
services:
  meanangular2:
    build: .
    image: 'meanangular2:1.0.0'
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
      image: 'mongo:3.4.4'
      ports:
        - "27017:27017"  