version: '2'
services:
    mongodb:
      image: mongo:3.4.10
      ports:
        - "27017:27017"
      networks:
        - db
            
    botportal:
      image: jenac/botportal
      environment:
        SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017"
        SPRING_DATA_MONGODB_DATABASE: chatbot-dev
        SERVER_PORT: 8443
        SERVER_SSL_KEY_STORE: /keystore/keystore.p12
        SERVER_SSL_KEY_STORE_PASSWORD: BotPortal$$123
        SERVER_SSL_KEY_STORE_TYPE: PKCS12
        SERVER_SSL_KEY_ALIAS: botportal
        SERVER_SSL_CIPHERS: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA,TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
        BOTSERVICE_HOST: http://chatbot:8888
      volumes:
        - "./keystore:/keystore"
      command: tail -f /app.war
      ports:
        - "8080:8080"
        - "8443:8443"
      networks:
        - db
    
    chatbot:
      image: jenac/chat-bot
      environment:
        - BOT_STORAGE_BASE=/app/data
        - BOT_MONGO_CONNECTION=mongodb://mongodb:27017/chatbot-dev
        - BOT_DATABASE=chatbot-dev
      ports:
        - "8888:8888"
      networks:
        - db
        
networks:
  db: