version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
    - HOST=db
    - USER="${DB_USER}"
    - PASSWORD="${DB_PASS}"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD="${DB_PASS}"
      - POSTGRES_USER="${DB_PASS}"