version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    # volumes:
    #   - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # ELASTIC_PASSWORD: changeme
      - cluster.name=elasticsearch-default
      - discovery.type=single-node
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    # volumes:
    #   - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge

    # image: docker.elastic.co/kibana/kibana:7.2.0
    # environment:
    #   SERVER_NAME: kibana.example.org
    #   ELASTICSEARCH_HOSTS: http://elasticsearch.example.org
