version: '2'
services:
  jenkins-docker:
    image: jenac/jenkins-docker
    restart: always
    ports:
      - "8080:8080"
    #hook with parent host's docker service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
