version: '2'

services:
  db:
    image: mariadb:10.4.5
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234@Abcd
      - MYSQL_PASSWORD=1234@Abcd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:15.0.8
    ports:
      - 80:80
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html
#      - data:/var/www/html/data
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=1234@Abcd
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.*
